Projet\BibliothequeBundle\Entity\Membre:
    type: entity
    table: null
    repositoryClass: Projet\BibliothequeBundle\Entity\MembreRepository
    manyToOne:
        faculte:
            targetEntity: Faculte
            inversedBy: membresFaculte
            cascade: [ persist ]
        cycle:
            targetEntity: Cycle
            inversedBy: membresCycle
            cascade: [ persist ]
    oneToMany:
        emprunts:
            targetEntity: Emprunt
            mappedBy: membreEmp
            orphanRemoval: true
        reservations:
            targetEntity: Reservation
            mappedBy: membreRes
            orphanRemoval: true
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: '25'
            column: Username
        password:
            type: string
            length: '15'
        nom:
            type: string
            length: '30'
        prenom:
            type: string
            length: '30'
    lifecycleCallbacks: {  }
