bibliotheque_livre:
    resource: "@BibliothequeBundle/Resources/config/routing/livre.yml"
    prefix:   /livre

bibliotheque_homepage:
    path:     /bibliotheque/accueil
    defaults: { _controller: BibliothequeBundle:Default:index}
