<?php

namespace BibliothequeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreRepository extends EntityRepository
{
	public function chercherParNomPart($str){
		$query = $this->getEntityManager()->createQuery
		("SELECT s FROM BibliothequeBundle:Membre s WHERE s.nom LIKE :str");
		$query->setParameter('str','%'.$str.'%');
		$membres = $query->getResult();
		return $membres;
	}
}
