exemplaire:
    path:     /
    defaults: { _controller: "ProjetBibliothequeBundle:Exemplaire:index" }

exemplaire_show:
    path:     /{id}/show
    defaults: { _controller: "ProjetBibliothequeBundle:Exemplaire:show" }

exemplaire_new:
    path:     /new
    defaults: { _controller: "ProjetBibliothequeBundle:Exemplaire:new" }

exemplaire_create:
    path:     /create
    defaults: { _controller: "ProjetBibliothequeBundle:Exemplaire:create" }
    requirements: { _method: post }

exemplaire_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProjetBibliothequeBundle:Exemplaire:edit" }

exemplaire_update:
    path:     /{id}/update
    defaults: { _controller: "ProjetBibliothequeBundle:Exemplaire:update" }
    requirements: { _method: post|put }

exemplaire_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProjetBibliothequeBundle:Exemplaire:delete" }
    requirements: { _method: post|delete }
