faculte:
    path:     /
    defaults: { _controller: "ProjetBibliothequeBundle:Faculte:index" }

faculte_show:
    path:     /{id}/show
    defaults: { _controller: "ProjetBibliothequeBundle:Faculte:show" }

faculte_new:
    path:     /new
    defaults: { _controller: "ProjetBibliothequeBundle:Faculte:new" }

faculte_create:
    path:     /create
    defaults: { _controller: "ProjetBibliothequeBundle:Faculte:create" }
    requirements: { _method: post }

faculte_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProjetBibliothequeBundle:Faculte:edit" }

faculte_update:
    path:     /{id}/update
    defaults: { _controller: "ProjetBibliothequeBundle:Faculte:update" }
    requirements: { _method: post|put }

faculte_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProjetBibliothequeBundle:Faculte:delete" }
    requirements: { _method: post|delete }
