membre:
    path:     /
    defaults: { _controller: "BibliothequeBundle:Membre:index" }

membre_show:
    path:     /{id}/show
    defaults: { _controller: "BibliothequeBundle:Membre:show" }

membre_new:
    path:     /new
    defaults: { _controller: "BibliothequeBundle:Membre:new" }

membre_search_by_nom:
    path:     /search_by_name
    defaults: { _controller: "BibliothequeBundle:Membre:chercherParNom" }

membre_create:
    path:     /create
    defaults: { _controller: "BibliothequeBundle:Membre:create" }
    requirements: { _method: post }

membre_edit:
    path:     /{id}/edit
    defaults: { _controller: "BibliothequeBundle:Membre:edit" }

membre_update:
    path:     /{id}/update
    defaults: { _controller: "BibliothequeBundle:Membre:update" }
    requirements: { _method: post|put }

membre_delete:
    path:     /{id}/delete
    defaults: { _controller: "BibliothequeBundle:Membre:delete" }
    requirements: { _method: post|delete }
