theme:
    path:     /
    defaults: { _controller: "BibliothequeBundle:Theme:index" }

theme_show:
    path:     /{id}/show
    defaults: { _controller: "BibliothequeBundle:Theme:show" }

theme_new:
    path:     /new
    defaults: { _controller: "BibliothequeBundle:Theme:new" }

theme_create:
    path:     /create
    defaults: { _controller: "BibliothequeBundle:Theme:create" }
    requirements: { _method: post }

theme_edit:
    path:     /{id}/edit
    defaults: { _controller: "BibliothequeBundle:Theme:edit" }

theme_update:
    path:     /{id}/update
    defaults: { _controller: "BibliothequeBundle:Theme:update" }
    requirements: { _method: post|put }

theme_delete:
    path:     /{id}/delete
    defaults: { _controller: "BibliothequeBundle:Theme:delete" }
    requirements: { _method: post|delete }
